"""phase4 forecasting

Revision ID: 0c13c421ea03
Revises: 6dfd70dd5f68
Create Date: 2026-09-10 09:09:27.589237

"""
from alembic import op
import sqlalchemy as sa


revision = '0c13c421ea03'
down_revision = '6dfd70dd5f68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_jobs',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('skus_processed', sa.Integer(), nullable=False),
    sa.Column('skus_skipped', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_jobs_sku_id'), 'forecast_jobs', ['sku_id'], unique=False)
    op.create_index(op.f('ix_forecast_jobs_warehouse_id'), 'forecast_jobs', ['warehouse_id'], unique=False)
    op.create_table('forecast_model_metrics',
    sa.Column('forecast_job_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('wape', sa.Float(), nullable=False),
    sa.Column('bias', sa.Float(), nullable=False),
    sa.Column('is_chosen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_model_metrics_forecast_job_id'), 'forecast_model_metrics', ['forecast_job_id'], unique=False)
    op.create_index(op.f('ix_forecast_model_metrics_sku_id'), 'forecast_model_metrics', ['sku_id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('forecast_job_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('horizon_date', sa.Date(), nullable=False),
    sa.Column('forecast_qty', sa.Float(), nullable=False),
    sa.Column('lower_ci', sa.Float(), nullable=True),
    sa.Column('upper_ci', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_job_id'], ['forecast_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_forecast_job_id'), 'forecast_results', ['forecast_job_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_sku_id'), 'forecast_results', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_results_sku_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_job_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_model_metrics_sku_id'), table_name='forecast_model_metrics')
    op.drop_index(op.f('ix_forecast_model_metrics_forecast_job_id'), table_name='forecast_model_metrics')
    op.drop_table('forecast_model_metrics')
    op.drop_index(op.f('ix_forecast_jobs_warehouse_id'), table_name='forecast_jobs')
    op.drop_index(op.f('ix_forecast_jobs_sku_id'), table_name='forecast_jobs')
    op.drop_table('forecast_jobs')
    # ### end Alembic commands ###
