"""phase7 make batch_number nullable

Revision ID: 5f4ebca7179a
Revises: ddc46a6d3ed1
Create Date: 2026-09-13 11:21:31.253068

"""
from alembic import op
import sqlalchemy as sa


revision = '5f4ebca7179a'
down_revision = 'ddc46a6d3ed1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
