"""phase3 skus sales inventory

Revision ID: 6dfd70dd5f68
Revises: a02680215332
Create Date: 2026-09-08 06:09:26.344819

"""
from alembic import op
import sqlalchemy as sa


revision = '6dfd70dd5f68'
down_revision = 'a02680215332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skus',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('storage_requirements', sa.JSON(), nullable=False),
    sa.Column('temperature_requirement', sa.String(length=50), nullable=True),
    sa.Column('fragility', sa.String(length=20), nullable=False),
    sa.Column('hazard_class', sa.String(length=50), nullable=False),
    sa.Column('min_qty', sa.Float(), nullable=True),
    sa.Column('max_qty', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('requires_expiry', sa.Boolean(), nullable=False),
    sa.Column('preferred_zone_id', sa.UUID(), nullable=True),
    sa.Column('picking_priority', sa.Integer(), nullable=False),
    sa.Column('fifo_required', sa.Boolean(), nullable=False),
    sa.Column('fefo_required', sa.Boolean(), nullable=False),
    sa.Column('lifo_permitted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'sku_code', name='uq_sku_customer_code')
    )
    op.create_index(op.f('ix_skus_customer_id'), 'skus', ['customer_id'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('receiving_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_sku_id'), 'inventory_batches', ['sku_id'], unique=False)
    op.create_table('sales_records',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('customer_segment', sa.String(length=100), nullable=True),
    sa.Column('sales_channel', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('promotion', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('holiday_flag', sa.Boolean(), nullable=False),
    sa.Column('returns', sa.Float(), nullable=False),
    sa.Column('stockout_flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_records_sale_date'), 'sales_records', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_records_sku_id'), 'sales_records', ['sku_id'], unique=False)
    op.create_index(op.f('ix_sales_records_warehouse_id'), 'sales_records', ['warehouse_id'], unique=False)
    op.create_table('inventory_records',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reserved_quantity', sa.Float(), nullable=False),
    sa.Column('damaged_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_location_id'], ['storage_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_records_batch_id'), 'inventory_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_current_location_id'), 'inventory_records', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_sku_id'), 'inventory_records', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_warehouse_id'), 'inventory_records', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_records_warehouse_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_sku_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_current_location_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_batch_id'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_sales_records_warehouse_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_sku_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_sale_date'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index(op.f('ix_inventory_batches_sku_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_skus_customer_id'), table_name='skus')
    op.drop_table('skus')
    # ### end Alembic commands ###
