"""phase2 layout zones and storage locations

Revision ID: a02680215332
Revises: cacd85c68357
Create Date: 2026-09-06 06:09:13.843765

"""
from alembic import op
import sqlalchemy as sa


revision = 'a02680215332'
down_revision = 'cacd85c68357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('hazard_class', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'zone_code', name='uq_zone_warehouse_code')
    )
    op.create_index(op.f('ix_zones_warehouse_id'), 'zones', ['warehouse_id'], unique=False)
    op.create_table('storage_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('location_code', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('aisle', sa.String(length=50), nullable=True),
    sa.Column('rack', sa.String(length=50), nullable=True),
    sa.Column('shelf', sa.String(length=50), nullable=True),
    sa.Column('bin', sa.String(length=50), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('max_volume', sa.Float(), nullable=True),
    sa.Column('used_capacity', sa.Float(), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('accessibility_level', sa.Integer(), nullable=False),
    sa.Column('dist_from_receiving', sa.Float(), nullable=True),
    sa.Column('dist_from_dispatch', sa.Float(), nullable=True),
    sa.Column('allowed_categories', sa.JSON(), nullable=False),
    sa.Column('temperature_restriction', sa.String(length=50), nullable=True),
    sa.Column('hazard_restriction', sa.String(length=50), nullable=True),
    sa.Column('fragility_restriction', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'location_code', name='uq_location_warehouse_code')
    )
    op.create_index(op.f('ix_storage_locations_warehouse_id'), 'storage_locations', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_storage_locations_zone_id'), 'storage_locations', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_locations_zone_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_warehouse_id'), table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_index(op.f('ix_zones_warehouse_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
