"""phase5 slotting recommendations

Revision ID: dc7629de529d
Revises: 0c13c421ea03
Create Date: 2026-09-11 20:31:39.861753

"""
from alembic import op
import sqlalchemy as sa


revision = 'dc7629de529d'
down_revision = '0c13c421ea03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_jobs',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('recommendations_created', sa.Integer(), nullable=False),
    sa.Column('inventory_records_evaluated', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_jobs_warehouse_id'), 'recommendation_jobs', ['warehouse_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('inventory_record_id', sa.UUID(), nullable=False),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('recommended_location_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.JSON(), nullable=False),
    sa.Column('expected_benefit', sa.Float(), nullable=False),
    sa.Column('distance_reduction', sa.Float(), nullable=True),
    sa.Column('demand_classification', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['storage_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_record_id'], ['inventory_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_inventory_record_id'), 'recommendations', ['inventory_record_id'], unique=False)
    op.create_index(op.f('ix_recommendations_sku_id'), 'recommendations', ['sku_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_warehouse_id'), 'recommendations', ['warehouse_id'], unique=False)
    op.create_table('recommendation_decisions',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('override_location_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['override_location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_decisions_recommendation_id'), 'recommendation_decisions', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_decisions_recommendation_id'), table_name='recommendation_decisions')
    op.drop_table('recommendation_decisions')
    op.drop_index(op.f('ix_recommendations_warehouse_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_sku_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_inventory_record_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_recommendation_jobs_warehouse_id'), table_name='recommendation_jobs')
    op.drop_table('recommendation_jobs')
    # ### end Alembic commands ###
