"""phase6 approval workflow and movement tasks

Revision ID: ddc46a6d3ed1
Revises: dc7629de529d
Create Date: 2026-09-11 20:41:59.436556

"""
from alembic import op
import sqlalchemy as sa


revision = 'ddc46a6d3ed1'
down_revision = 'dc7629de529d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_tasks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('inventory_record_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['inventory_record_id'], ['inventory_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_tasks_inventory_record_id'), 'movement_tasks', ['inventory_record_id'], unique=False)
    op.create_index(op.f('ix_movement_tasks_recommendation_id'), 'movement_tasks', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_movement_tasks_status'), 'movement_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_movement_tasks_warehouse_id'), 'movement_tasks', ['warehouse_id'], unique=False)
    op.create_table('movement_confirmations',
    sa.Column('movement_task_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movement_task_id'], ['movement_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_confirmations')
    op.drop_index(op.f('ix_movement_tasks_warehouse_id'), table_name='movement_tasks')
    op.drop_index(op.f('ix_movement_tasks_status'), table_name='movement_tasks')
    op.drop_index(op.f('ix_movement_tasks_recommendation_id'), table_name='movement_tasks')
    op.drop_index(op.f('ix_movement_tasks_inventory_record_id'), table_name='movement_tasks')
    op.drop_table('movement_tasks')
    # ### end Alembic commands ###
